

version: "1"
services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017
    links:
      -  mongod-service

    volumes:
      - ./data:/data/db

  mongod-service:
    image: springlearn:latest
    container_name: "springlearncompose"
    build:
      context: ../../../
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    container_name: "rabbitmq"

    links:
      - mongod-service
    ports:
      - 5672:5672
      - 15672:15672
